#!/usr/bin/env php
<?
// Copyright (c) 2010 Guanoo, Inc.
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.

$YAWF_ROOT = getenv('YAWF_ROOT');
if (!$YAWF_ROOT || !is_dir($YAWF_ROOT) || !is_dir("$YAWF_ROOT/yawf"))
{
    print "\nPlease set the YAWF_ROOT environment variable\nto the folder name where YAWF may be found on\nyour computer, e.g. ~/cloud/projects/YAWF\n\n";
    exit;
}

require "$YAWF_ROOT/yawf/lib/Command.php";

class Yet_another_shell extends Command
{
    protected $is_quiet;

    // Methods

    public function __construct()
    {
        parent::__construct();
        $this->is_quiet = $this->opts->quiet;
    }

    // Run the YAWF shell

    public function run()
    {
        global $app;
        $stdin = fopen('php://stdin', 'r');
        $this->say('> ');
        while ($line = fgets($stdin))
        {
            $line = rtrim(trim($line), ';');
            if ($line == 'quit') exit;
            if ($line === '') $line = 'NULL';
            if (preg_match('/^(#|\/\/)/', $line)) continue; # comments
            $line = $this->parse($line);
            try
            {
                $result = NULL;
                $command_regexp = '/^[a-z]\w*\s+/';
                eval(preg_match($command_regexp, $line) ? "$line;"
                                                        : "\$result=($line);");
                $this->say(print_r($result, TRUE) . "\n");
            }
            catch (Exception $e)
            {
                print "ERROR: $e\n";
            }
            $this->say('> ');
        }
        $this->say("\n");
    }

    // Parse "p", "puts", "should" and "should_not" commands

    protected function parse($line)
    {
        $line = preg_replace('/^p\s+(.*)$/', 'print_r(\1)', $line);
        $line = preg_replace('/^puts\s+(.*)$/', 'print(\1 . "\n")', $line);
        $line = preg_replace('/^should[_\s]not\s+(.*)$/', '$this->should_not(\1)', $line);
        $line = preg_replace('/^should\s+(.*)$/', '$this->should(\1)', $line);
        return $line;
    }

    // Say something unless we're being quiet

    public function say($text)
    {
        if (!$this->is_quiet) print $text;
    }

    // Parse lines like "$this->should('work', 1==1)" in yash scripts

    public function should($test, $is_ok, $var = NULL)
    {
        $text = $is_ok ? 'Pass' : 'Fail';
        $text .= ": should $test";
        if ($is_ok)
        {
            Log::info($text);
        }
        else
        {
            if (!is_null($var)) $text .= "\n\n" . print_r($var, TRUE);
            Log::error($text);
        }
        print "$text\n";
        return $is_ok;
    }

    // Parse lines like "$this->should_not('fail', 1==2)" in yash scripts

    public function should_not($text, $bool, $var = NULL)
    {
        return $this->should("not $text", !$bool, $var);
    }
}

$yash = new Yet_another_shell(getcwd());
$app = $yash->app;
$yash->run();

// End of "commands/yash"
