#!/usr/bin/env php
<?
// Copyright (c) 2010 Guanoo, Inc.
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.

$YAWF_ROOT = getenv('YAWF_ROOT');
if (!$YAWF_ROOT || !is_dir($YAWF_ROOT) || !is_dir("$YAWF_ROOT/yawf"))
{
    print "\nPlease set the YAWF_ROOT environment variable\nto the folder name where YAWF may be found on\nyour computer, e.g. ~/cloud/projects/YAWF\n\n";
    exit;
}

require "$YAWF_ROOT/yawf/lib/Command.php";

class Yet_another_shell extends Command
{
    // Methods

    // Run the YAWF shell

    public function run()
    {
        global $app;
        $stdin = fopen('php://stdin', 'r');
        print '> ';
        while ($line = fgets($stdin))
        {
            $line = rtrim(trim($line), ';');
            if ($line == 'quit') exit;
            if ($line === '') $line = 'NULL';
            if (preg_match('/^(#|\/\/)/', $line)) continue; # comments
            try
            {
                $result = NULL;
                $command_regexp = '/^[a-z]\w*\s+/';
                eval(preg_match($command_regexp, $line) ? "$line;"
                                                        : "\$result=($line);");
                print_r($result);
                print "\n";
            }
            catch (Exception $e)
            {
                print "ERROR: $e\n";
            }
            print '> ';
        }
        print "\n";
    }

    // Parse lines like "$this->should('work', 1==1)" in yash scripts

    public function should($test, $is_ok, $var = NULL)
    {
        $text = $is_ok ? 'Pass' : 'Fail';
        $text .= ": should $test";
        if ($is_ok)
        {
            Log::info($text);
        }
        else
        {
            if (!is_null($var)) $text .= "\n" . print_r($var, TRUE);
            Log::error($text);
        }
        return $text;
    }

    // Parse lines like "$this->should_not('fail', 1==2)" in yash scripts

    public function should_not($text, $bool, $var = NULL)
    {
        return $this->should("not $text", !$bool, $var);
    }
}

$yash = new Yet_another_shell(getcwd());
$app = $yash->app;
$yash->run();

// End of "commands/yash"
