#!/bin/bash

# Copyright (c) 2010 Guanoo, Inc.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.

command=$1; shift
usage="usage: yawf_daemon start|stop daemon [daemon2...]"
if [ $# -eq 0 ] ; then
  echo $usage; exit 1
fi

for daemon in $*; do

  # Get the app dir

  app_dir=`which $daemon`
  if [ -n "$app_dir" ] ; then
    app_dir=`dirname $app_dir`
    app_dir=`dirname $app_dir`
  else
    echo $usage; exit 1
  fi

  # Start or stop the daemon

  case "$command" in
  start)
    log="$app_dir/logs/daemon.log"
    echo Starting $daemon
    nohup $daemon >> $log &
    ;;
  stop)
    echo Stopping $daemon
    pid_file="$app_dir/tmp/pids/$daemon.pid"
    if [ -f $pid_file ] ; then
      pid=`cat $pid_file`
      kill $pid
      rm -f $pid_file
    else
      echo "Daemon $daemon is not running"
    fi
    ;;
  *)
    echo $usage
    ;;
  esac
done

# End of "yawf_daemon"
