#!/usr/bin/env php
<?
// Copyright (c) 2009 Guanoo, Inc.
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.

$YAWF_ROOT = getenv('YAWF_ROOT');
if (!$YAWF_ROOT || !is_dir($YAWF_ROOT) || !is_dir("$YAWF_ROOT/yawf"))
{
    print "\nPlease set the YAWF_ROOT environment variable\nto the folder name where YAWF may be found on\nyour computer, e.g. ~/cloud/projects/YAWF\n\n";
    exit;
}

require "$YAWF_ROOT/yawf/lib/Command.php";

class YAWF_shell extends Command
{
    // Methods

    // Run the YAWF shell

    public function run()
    {
        $stdin = fopen ("php://stdin","r");
        print '> ';
        while ($line = fgets($stdin))
        {
            try
            {
                $result = NULL;
                $command_regexp = '/^\s*[a-z]\w*\s+/';
                eval(preg_match($command_regexp, $line) ? "$line;"
                                                        : "\$result=($line);");
                $out = is_null($result) ? '' : var_export($result, TRUE);
                print "$out\n";
            }
            catch (Exception $e)
            {
                print "ERROR: $e\n";
            }
            print '> ';
        }
    }
}

$ysh = new YAWF_shell(getcwd());
$ysh->run();

// End of "admin/yawf"
