#!/usr/bin/env php
<?
require getenv('YAWF_ROOT') . '/yawf/lib/App_command.php';

class MyApp_command extends App_command
{
    // TODO: Override "start" and "stop" methods as needed
}

$command = new MyApp_command();
$command->run();

// End of the MyApp command
