#!/usr/bin/env php
<?
require getenv('YAWF_ROOT') . '/yawf/lib/Command.php';

class Fuzzy_command extends Command
{
    const USAGE = 'usage: fuzzy -rules=rules.txt -facts=facts.txt';

    public function run()
    {
        load_plugin('Logic/FuzzySure');

        $rules = $this->opts->rules;
        $facts = $this->opts->facts;
        if (!$rules || !$facts) $this->quit(self::USAGE);

        $memory = $this->opts->debug ? array('DEBUG' => TRUE) : NULL;
        $sure = new FuzzySure($this->opts->limit);
        $sure->with($rules)->given($facts)->infer($memory);
        if ($this->opts->dump) print json_encode((array)$sure->memory());
    }
}

$fuzzy = new Fuzzy_command();
$fuzzy->run();

// End of fuzzy
