en:
    "default/index": Welcome to Yet Another Web Framework
    "project/cookbook": Cookbook
    "project/download": Download
    "project/faq": FAQ
    "project/forum": Forum
    "project/news": News
    "project/code": Code browser
    "project/terms": Terms &amp; Conditions

es:
    "default/index": Welcome to Yet Another Web Framework
    "project/cookbook": Cookbook
    "project/download": Download
    "project/faq": FAQ
    "project/forum": Forum
    "project/news": News
    "project/code": Code browser
    "project/terms": Terms &amp; Conditions
